import { ArrowLeft, Plus, Scale, TrendingDown, TrendingUp, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useNavigate } from "react-router-dom";
import { useToast } from "../../app/ToastProvider";
import { Button, Card, EmptyState, PageHeader, Skeleton } from "../../components/ui";
import { apiMutation } from "../../lib/api";
import { useApi } from "../../lib/use-api";

interface WeightProgress { current: number | null; previous: number | null; difference: number | null; weekly: Array<{ weekStart: string; averageKg: number; samples: number }>; measurements: Array<{ id: string; measuredAt: string; weightKg: number; waistCm: number | null; hipCm: number | null; thighCm: number | null; calfCm: number | null }> }
const blank = { weightKg: "", waistCm: "", hipCm: "", chestCm: "", armCm: "", thighCm: "", calfCm: "", bodyFatPercentage: "", notes: "" };
export function BodyProgressPage() {
  const navigate = useNavigate(); const { show } = useToast(); const { data, loading, refresh } = useApi<WeightProgress>("/api/progress/weight"); const [modal, setModal] = useState(false); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const numeric = Object.fromEntries(Object.entries(form).map(([key, value]) => key === "notes" ? [key, value] : [key, value === "" ? null : Number(value)])); const result = await apiMutation<{ queued?: boolean }>("/api/measurements", "POST", { ...numeric, measuredAt: new Date().toISOString(), idempotencyKey: crypto.randomUUID() }, true); show(result.queued ? "Medida guardada. Não sincronizado." : "Medida registrada.", result.queued ? "info" : "success"); setModal(false); setForm(blank); if (!result.queued) await refresh(); } catch (error) { show(error instanceof Error ? error.message : "Não foi possível registrar.", "error"); } finally { setSaving(false); } };
  if (loading) return <div className="page-stack"><Skeleton className="chart-skeleton" /></div>;
  return <div className="page-stack body-progress"><button className="back-link" onClick={() => navigate(-1)}><ArrowLeft /> Progresso</button><PageHeader eyebrow="CORPO" title="Peso e medidas" action={<Button onClick={() => setModal(true)}><Plus /> REGISTRAR</Button>} /><div className="metric-grid body-metrics"><Card><span>PESO ATUAL</span><strong>{data?.current != null ? `${data.current.toFixed(1)} kg` : "—"}</strong></Card><Card><span>ANTERIOR</span><strong>{data?.previous != null ? `${data.previous.toFixed(1)} kg` : "—"}</strong></Card><Card><span>DIFERENÇA</span><strong className={(data?.difference ?? 0) <= 0 ? "trend-good" : ""}>{data?.difference != null ? <>{data.difference <= 0 ? <TrendingDown /> : <TrendingUp />}{data.difference > 0 ? "+" : ""}{data.difference.toFixed(1)} kg</> : "—"}</strong></Card><Card><span>MÉDIA SEMANAL</span><strong>{data?.weekly.at(-1)?.averageKg.toFixed(1) ?? "—"}<small> kg</small></strong></Card></div>
    <Card className="chart-card"><div className="section-heading"><div><span className="eyebrow">TENDÊNCIA</span><h2>Peso médio por semana</h2></div><small>A média usa os registros disponíveis.</small></div>{data?.weekly.length ? <ResponsiveContainer width="100%" height={290}><LineChart data={data.weekly}><CartesianGrid strokeDasharray="4 4" stroke="rgba(255,255,255,.08)" /><XAxis dataKey="weekStart" tickFormatter={(value) => value.slice(5)} stroke="#69736d" /><YAxis domain={["dataMin - 1", "dataMax + 1"]} stroke="#69736d" /><Tooltip contentStyle={{ background: "#171c19", border: "1px solid #29322d", borderRadius: 12 }} /><Line type="monotone" dataKey="averageKg" stroke="var(--accent)" strokeWidth={3} dot={{ fill: "var(--accent)", strokeWidth: 0 }} /></LineChart></ResponsiveContainer> : <EmptyState icon={<Scale />} title="Sem pesos registrados" text="Registre seu peso em condições semelhantes para formar uma tendência semanal." />}</Card>
    <Card className="measurement-history"><div className="section-heading"><div><span className="eyebrow">REGISTROS</span><h2>Histórico recente</h2></div></div>{data?.measurements.slice(-8).reverse().map((item) => <div key={item.id}><span>{new Date(item.measuredAt).toLocaleDateString("pt-BR")}</span><strong>{item.weightKg.toFixed(1)} kg</strong></div>)}</Card>
    {modal && <div className="modal-layer" role="dialog" aria-modal="true"><button className="modal-backdrop" onClick={() => setModal(false)} /><Card className="measurement-modal"><button className="modal-close" onClick={() => setModal(false)}><X /></button><span className="eyebrow">NOVO REGISTRO</span><h2>Peso e medidas</h2><p>Preencha apenas o que mediu hoje.</p><form onSubmit={(event) => void submit(event)}><div className="measurement-form-grid">{Object.entries({ weightKg: "Peso (kg)", waistCm: "Cintura (cm)", hipCm: "Quadril (cm)", chestCm: "Peito (cm)", armCm: "Braço (cm)", thighCm: "Coxa (cm)", calfCm: "Panturrilha (cm)", bodyFatPercentage: "Gordura estimada (%)" }).map(([key, label]) => <label key={key}>{label}<input type="number" inputMode="decimal" step="0.1" min="0" value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}</div><label>Observação<textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label><Button type="submit" loading={saving}>SALVAR REGISTRO</Button></form></Card></div>}
  </div>;
}
