CREATE TABLE users (id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, last_used_at TEXT NOT NULL, user_agent_hash TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX sessions_user_expires_idx ON sessions(user_id, expires_at);
CREATE TABLE login_attempts (key_hash TEXT PRIMARY KEY, attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts >= 0), window_started_at TEXT NOT NULL, blocked_until TEXT, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE athlete_profiles (id TEXT PRIMARY KEY, user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, sex TEXT NOT NULL, height_cm INTEGER CHECK(height_cm IS NULL OR height_cm BETWEEN 80 AND 260), current_weight_grams INTEGER CHECK(current_weight_grams IS NULL OR current_weight_grams BETWEEN 20000 AND 400000), program_start_date TEXT NOT NULL, current_program_id TEXT, timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo', theme_key TEXT NOT NULL DEFAULT 'dark', accent_color TEXT NOT NULL DEFAULT '#79f2b0', version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(current_program_id, id) REFERENCES training_programs(id, athlete_profile_id));
CREATE TABLE training_programs (id TEXT PRIMARY KEY, athlete_profile_id TEXT NOT NULL REFERENCES athlete_profiles(id) ON DELETE CASCADE, program_key TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, source_research TEXT NOT NULL, duration_weeks INTEGER NOT NULL DEFAULT 52 CHECK(duration_weeks > 0), version TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), progression_policy TEXT NOT NULL, recovery_policy TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(id, athlete_profile_id), UNIQUE(athlete_profile_id, program_key, version));
CREATE INDEX training_program_profile_active_idx ON training_programs(athlete_profile_id, active);
CREATE TABLE training_blocks (id TEXT PRIMARY KEY, program_id TEXT NOT NULL REFERENCES training_programs(id) ON DELETE CASCADE, block_number INTEGER NOT NULL CHECK(block_number BETWEEN 1 AND 4), name TEXT NOT NULL, start_week INTEGER NOT NULL, end_week INTEGER NOT NULL, objective TEXT NOT NULL, description TEXT NOT NULL, differences TEXT NOT NULL, volume_summary TEXT NOT NULL, CHECK(start_week > 0 AND end_week >= start_week), UNIQUE(program_id, block_number));
CREATE TABLE training_days (id TEXT PRIMARY KEY, block_id TEXT NOT NULL REFERENCES training_blocks(id) ON DELETE CASCADE, weekday INTEGER NOT NULL CHECK(weekday BETWEEN 1 AND 7), name TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'strength', order_index INTEGER NOT NULL, description TEXT NOT NULL DEFAULT '', duration_min INTEGER, duration_max INTEGER, UNIQUE(block_id, order_index), UNIQUE(block_id, weekday));
CREATE TABLE exercises (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, muscle_group TEXT NOT NULL, equipment TEXT, instructions TEXT NOT NULL DEFAULT '');
CREATE TABLE exercise_prescriptions (id TEXT PRIMARY KEY, training_day_id TEXT NOT NULL REFERENCES training_days(id) ON DELETE CASCADE, exercise_id TEXT NOT NULL REFERENCES exercises(id), order_index INTEGER NOT NULL, sets INTEGER NOT NULL CHECK(sets BETWEEN 1 AND 20), reps_min INTEGER NOT NULL, reps_max INTEGER NOT NULL, reps_label TEXT, rir_min INTEGER NOT NULL CHECK(rir_min BETWEEN 0 AND 10), rir_max INTEGER NOT NULL CHECK(rir_max BETWEEN rir_min AND 10), rir_direction TEXT, rest_seconds_min INTEGER NOT NULL, rest_seconds_max INTEGER NOT NULL, technique_notes TEXT NOT NULL DEFAULT '', progression_notes TEXT NOT NULL DEFAULT '', primary_muscle TEXT NOT NULL, secondary_muscles TEXT NOT NULL DEFAULT '', category TEXT NOT NULL, is_effective_set INTEGER NOT NULL DEFAULT 1 CHECK(is_effective_set IN (0,1)), requires_selection INTEGER NOT NULL DEFAULT 0 CHECK(requires_selection IN (0,1)), CHECK(reps_min > 0 AND reps_max >= reps_min), CHECK(rest_seconds_min > 0 AND rest_seconds_max >= rest_seconds_min), UNIQUE(training_day_id, order_index));
CREATE INDEX exercise_prescriptions_exercise_idx ON exercise_prescriptions(exercise_id);
CREATE TABLE cardio_prescriptions (id TEXT PRIMARY KEY, block_id TEXT NOT NULL REFERENCES training_blocks(id) ON DELETE CASCADE, weekday INTEGER NOT NULL CHECK(weekday BETWEEN 1 AND 7), modality TEXT NOT NULL, duration_min INTEGER NOT NULL, duration_max INTEGER NOT NULL, intensity TEXT NOT NULL, rpe_min INTEGER NOT NULL CHECK(rpe_min BETWEEN 0 AND 10), rpe_max INTEGER NOT NULL CHECK(rpe_max BETWEEN rpe_min AND 10), instructions TEXT NOT NULL, recovery_notes TEXT NOT NULL, optional_interval_protocol TEXT, CHECK(duration_min > 0 AND duration_max >= duration_min), UNIQUE(block_id, weekday));
CREATE TABLE science_topics (id TEXT PRIMARY KEY, program_id TEXT NOT NULL REFERENCES training_programs(id) ON DELETE CASCADE, category TEXT NOT NULL, title TEXT NOT NULL, summary TEXT NOT NULL, order_index INTEGER NOT NULL, UNIQUE(program_id, category));
CREATE TABLE science_references (id TEXT PRIMARY KEY, program_id TEXT NOT NULL REFERENCES training_programs(id) ON DELETE CASCADE, topic_category TEXT NOT NULL, title TEXT NOT NULL, doi TEXT, pmid TEXT, url TEXT NOT NULL, UNIQUE(program_id, url));
