CREATE TABLE workout_sessions (id TEXT PRIMARY KEY, athlete_profile_id TEXT NOT NULL REFERENCES athlete_profiles(id) ON DELETE CASCADE, training_day_id TEXT NOT NULL REFERENCES training_days(id), scheduled_date TEXT NOT NULL, original_scheduled_date TEXT NOT NULL, started_at TEXT, finished_at TEXT, status TEXT NOT NULL DEFAULT 'scheduled' CHECK(status IN ('scheduled','in_progress','completed','missed','skipped','rescheduled','partial')), notes TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(athlete_profile_id, training_day_id, scheduled_date));
CREATE INDEX workout_sessions_profile_date_idx ON workout_sessions(athlete_profile_id, scheduled_date);
CREATE TABLE exercise_logs (id TEXT PRIMARY KEY, workout_session_id TEXT NOT NULL REFERENCES workout_sessions(id) ON DELETE CASCADE, exercise_prescription_id TEXT NOT NULL REFERENCES exercise_prescriptions(id), exercise_id TEXT NOT NULL REFERENCES exercises(id), completed INTEGER NOT NULL DEFAULT 0 CHECK(completed IN (0,1)), technique_confirmed INTEGER NOT NULL DEFAULT 0 CHECK(technique_confirmed IN (0,1)), notes TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(workout_session_id, exercise_prescription_id));
CREATE INDEX exercise_logs_exercise_idx ON exercise_logs(exercise_id);
CREATE TABLE set_logs (id TEXT PRIMARY KEY, exercise_log_id TEXT NOT NULL REFERENCES exercise_logs(id) ON DELETE CASCADE, set_number INTEGER NOT NULL CHECK(set_number BETWEEN 1 AND 20), load_grams INTEGER CHECK(load_grams IS NULL OR load_grams BETWEEN 0 AND 1000000), reps INTEGER CHECK(reps IS NULL OR reps BETWEEN 0 AND 200), actual_rir INTEGER CHECK(actual_rir IS NULL OR actual_rir BETWEEN 0 AND 10), completed INTEGER NOT NULL DEFAULT 0 CHECK(completed IN (0,1)), idempotency_key TEXT UNIQUE, version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(exercise_log_id, set_number));

CREATE TABLE body_measurements (id TEXT PRIMARY KEY, athlete_profile_id TEXT NOT NULL REFERENCES athlete_profiles(id) ON DELETE CASCADE, measured_at TEXT NOT NULL, weight_grams INTEGER CHECK(weight_grams IS NULL OR weight_grams BETWEEN 20000 AND 400000), waist_mm INTEGER, hip_mm INTEGER, chest_mm INTEGER, arm_mm INTEGER, thigh_mm INTEGER, calf_mm INTEGER, body_fat_basis_points INTEGER CHECK(body_fat_basis_points IS NULL OR body_fat_basis_points BETWEEN 100 AND 7000), notes TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX body_measurements_profile_date_idx ON body_measurements(athlete_profile_id, measured_at);
CREATE TABLE program_state (athlete_profile_id TEXT PRIMARY KEY REFERENCES athlete_profiles(id) ON DELETE CASCADE, current_week INTEGER NOT NULL CHECK(current_week BETWEEN 1 AND 52), current_block INTEGER NOT NULL CHECK(current_block BETWEEN 1 AND 4), manual_override INTEGER NOT NULL DEFAULT 0 CHECK(manual_override IN (0,1)), version INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE program_state_history (id TEXT PRIMARY KEY, athlete_profile_id TEXT NOT NULL REFERENCES athlete_profiles(id) ON DELETE CASCADE, previous_week INTEGER NOT NULL, new_week INTEGER NOT NULL, reason TEXT NOT NULL, changed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX program_state_history_profile_idx ON program_state_history(athlete_profile_id, changed_at);
CREATE TABLE calendar_overrides (id TEXT PRIMARY KEY, athlete_profile_id TEXT NOT NULL REFERENCES athlete_profiles(id) ON DELETE CASCADE, original_date TEXT NOT NULL, new_date TEXT, training_day_id TEXT REFERENCES training_days(id), action TEXT NOT NULL CHECK(action IN ('rescheduled','missed','rest')), reason TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(athlete_profile_id, original_date, training_day_id));
CREATE INDEX calendar_overrides_profile_new_date_idx ON calendar_overrides(athlete_profile_id, new_date);
CREATE TABLE cardio_sessions (id TEXT PRIMARY KEY, athlete_profile_id TEXT NOT NULL REFERENCES athlete_profiles(id) ON DELETE CASCADE, cardio_prescription_id TEXT REFERENCES cardio_prescriptions(id), scheduled_date TEXT NOT NULL, started_at TEXT, finished_at TEXT, status TEXT NOT NULL DEFAULT 'scheduled' CHECK(status IN ('scheduled','in_progress','completed','missed','skipped')), modality TEXT NOT NULL, actual_duration_minutes INTEGER, actual_rpe INTEGER CHECK(actual_rpe IS NULL OR actual_rpe BETWEEN 0 AND 10), notes TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX cardio_sessions_profile_date_idx ON cardio_sessions(athlete_profile_id, scheduled_date);
CREATE TABLE recovery_checkins (id TEXT PRIMARY KEY, athlete_profile_id TEXT NOT NULL REFERENCES athlete_profiles(id) ON DELETE CASCADE, week_number INTEGER NOT NULL CHECK(week_number BETWEEN 1 AND 52), checked_at TEXT NOT NULL, performance_dropped INTEGER NOT NULL, poor_sleep INTEGER NOT NULL, persistent_soreness INTEGER NOT NULL, joint_pain INTEGER NOT NULL, low_motivation INTEGER NOT NULL, high_fatigue INTEGER NOT NULL, rir_loss INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('green','yellow','red','pain')), recommendation TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(athlete_profile_id, week_number));
CREATE TABLE extra_activities (id TEXT PRIMARY KEY, athlete_profile_id TEXT NOT NULL REFERENCES athlete_profiles(id) ON DELETE CASCADE, activity_date TEXT NOT NULL, name TEXT NOT NULL, duration_minutes INTEGER, rpe INTEGER, notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX extra_activities_profile_date_idx ON extra_activities(athlete_profile_id, activity_date);
CREATE TABLE seed_runs (seed_key TEXT NOT NULL, seed_version TEXT NOT NULL, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(seed_key, seed_version));
